FROM python:3-alpine
USER root

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /home/test/Desktop/web_site

COPY . .

RUN python -m pip install django

RUN python -m pip install requests

RUN python -m pip install unittest

CMD ["python3", "test_api.py"]
